name: Code quality checks
on:
  pull_request:
    branches:
      - devel-*
jobs:
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      # Check out branch
      - uses: actions/checkout@v3
      # Set up a JDK, configure a local cache for Maven dependencies
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
          architecture: x64
          cache: maven
      # Run Maven
      - name: Run mvn verify
        run: mvn -B clean verify -Dmaven.test.failure.ignore=true
      # Get the overall coverage value and format
      - name: Extract branch coverage value
        id: report-coverage
        uses: .github/actions/report-coverage-action
        with:
          output-file: ${{github.workspace}}/target/site/jacoco/jacoco.xml
          elements: branch
      # Add a comment on the PR with the test coverage value
      - name: Upsert comment on PR
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          message: Branch code coverage reported as ${{ steps.report-coverage.outputs.branchCoverage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
